# Splitting of Dataset

<h2> Importing Libraries </h2>

In [1]:
import pandas as pd
import numpy as np

<h2> Importing Dataset </h2>

In [2]:
df = pd.read_excel("Salary_Dataset_02.xls")

In [3]:
df.head()

   Australia  Canada  Dubai  USA  Salary  YearsExperience  Purchased
0          0       0      1    0   39343              1.1          0
1          0       1      0    0   46205              1.3          1
2          0       1      0    0   37731              1.5          0
3          0       1      0    0   43525              2.0          0
4          0       0      0    1   39891              2.2          0

<h2> Dividing into Target and Predictor Variables </h2>

In [4]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

<h2> Divide Data as Training Set and Testing Set </h2>

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 56)

In [7]:
X_train

    Australia  Canada  Dubai  USA  Salary  YearsExperience
19          0       1      0    0   93940              6.0
8           0       0      1    0   64445              3.2
18          1       0      0    0   81363              5.9
22          1       0      0    0  101302              7.9
1           0       1      0    0   46205              1.3
6           0       1      0    0   60150              3.0
5           0       0      1    0   56642              2.9
26          0       0      1    0  116969              9.5
23          1       0      0    0  113812              8.2
16          0       0      0    1   66029              5.1
24          0       0      1    0  109431              8.7
25          1       0      0    0  105582              9.0
12          0       0      1    0   56957              4.0
17          0       1      0    0   83088              5.3
27          0       0      0    1  112635              9.6
28          0       0      0    1  122391             10.3
9           0       0      1    0   57189              3.7
14          1       0      0    0   61111              4.5
11          0       0      0    1   55794              4.0
2           0       1      0    0   37731              1.5
0           0       0      1    0   39343              1.1
15          0       0      0    1   67938              4.9
4           0       0      0    1   39891              2.2
21          1       0      0    0   98273              7.1

In [8]:
X_test

    Australia  Canada  Dubai  USA  Salary  YearsExperience
13          0       1      0    0   57081              4.1
20          0       1      0    0   91738              6.8
7           1       0      0    0   54445              3.2
3           0       1      0    0   43525              2.0
10          0       0      1    0   63218              3.9
29          0       1      0    0  121872             10.5

In [9]:
y_train

19    0
8     1
18    1
22    0
1     1
6     1
5     0
26    0
23    1
16    0
24    0
25    1
12    1
17    0
27    1
28    0
9     0
14    0
11    0
2     0
0     0
15    0
4     0
21    0
Name: Purchased, dtype: int64

In [10]:
y_test

13    0
20    0
7     0
3     0
10    1
29    1
Name: Purchased, dtype: int64